
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u";\u01f4\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\3\2\3\2\3\3\6\3}\n\3\r\3\16\3")
        buf.write(u"~\3\3\3\3\3\4\3\4\3\5\3\5\3\6\3\6\3\7\3\7\3\b\3\b\3\t")
        buf.write(u"\3\t\3\n\3\n\3\13\3\13\3\f\3\f\3\r\3\r\3\16\3\16\3\17")
        buf.write(u"\3\17\3\17\3\17\3\17\3\20\3\20\3\20\3\20\3\20\3\20\3")
        buf.write(u"\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write(u"\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3")
        buf.write(u"\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write(u"\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3")
        buf.write(u"\20\3\20\3\20\3\20\3\20\3\20\3\20\5\20\u00d5\n\20\3\21")
        buf.write(u"\3\21\3\21\3\21\3\21\3\22\3\22\3\22\3\22\3\22\3\23\3")
        buf.write(u"\23\3\23\3\23\3\23\3\23\3\24\3\24\3\24\3\24\3\24\3\25")
        buf.write(u"\3\25\3\25\3\25\3\26\3\26\3\26\3\26\3\26\3\27\3\27\3")
        buf.write(u"\27\3\27\3\27\3\30\3\30\3\30\3\30\3\30\3\31\3\31\3\31")
        buf.write(u"\3\31\3\31\3\32\3\32\3\32\3\32\3\32\3\33\3\33\3\33\3")
        buf.write(u"\33\3\33\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\35")
        buf.write(u"\3\35\3\35\3\35\3\35\3\35\3\35\3\35\3\36\3\36\3\36\3")
        buf.write(u"\36\3\36\3\36\3\36\3\36\3\37\3\37\3\37\3\37\3\37\3\37")
        buf.write(u"\3\37\3\37\3 \3 \3 \3 \3 \3 \3 \3 \3!\3!\3!\3!\3!\3!")
        buf.write(u"\3!\3!\3\"\3\"\3\"\3\"\3\"\3\"\3#\3#\3#\3#\3#\3#\3$\3")
        buf.write(u"$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&")
        buf.write(u"\3&\3&\3&\3\'\3\'\3\'\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3")
        buf.write(u"(\3(\3(\3)\3)\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3*\3+\3+")
        buf.write(u"\3+\3+\3+\3,\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3-\3-\3-\3")
        buf.write(u".\3.\3/\3/\3\60\3\60\3\61\3\61\3\62\3\62\7\62\u0198\n")
        buf.write(u"\62\f\62\16\62\u019b\13\62\3\62\3\62\3\62\6\62\u01a0")
        buf.write(u"\n\62\r\62\16\62\u01a1\5\62\u01a4\n\62\3\63\3\63\3\64")
        buf.write(u"\3\64\3\65\6\65\u01ab\n\65\r\65\16\65\u01ac\3\65\3\65")
        buf.write(u"\3\65\3\65\3\65\7\65\u01b4\n\65\f\65\16\65\u01b7\13\65")
        buf.write(u"\3\65\7\65\u01ba\n\65\f\65\16\65\u01bd\13\65\3\65\3\65")
        buf.write(u"\3\65\3\65\3\65\7\65\u01c4\n\65\f\65\16\65\u01c7\13\65")
        buf.write(u"\3\65\3\65\6\65\u01cb\n\65\r\65\16\65\u01cc\5\65\u01cf")
        buf.write(u"\n\65\3\66\3\66\3\67\3\67\38\38\38\38\38\39\39\3:\3:")
        buf.write(u"\3:\3:\3:\3;\3;\3<\3<\6<\u01e5\n<\r<\16<\u01e6\3<\5<")
        buf.write(u"\u01ea\n<\3<\6<\u01ed\n<\r<\16<\u01ee\3<\3<\5<\u01f3")
        buf.write(u"\n<\3\u0199\2=\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23")
        buf.write(u"\13\25\f\27\r\31\16\33\17\35\20\37\21!\22#\23%\24\'\25")
        buf.write(u")\26+\27-\30/\31\61\32\63\33\65\34\67\359\36;\37= ?!")
        buf.write(u"A\"C#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\2c\62e\63g\2")
        buf.write(u"i\64k\65m\66o\67q8s9u:w;\3\2\7\5\2\13\f\17\17\"\"\4\2")
        buf.write(u"C\\c|\3\2\62;\4\2\"\"<=\4\2..<=\2\u0203\2\3\3\2\2\2\2")
        buf.write(u"\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3")
        buf.write(u"\2\2\2\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3")
        buf.write(u"\2\2\2\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3")
        buf.write(u"\2\2\2\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2")
        buf.write(u"\2\'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2")
        buf.write(u"\2\2\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3\2")
        buf.write(u"\2\2\29\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2A\3")
        buf.write(u"\2\2\2\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2\2")
        buf.write(u"K\3\2\2\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2S\3\2\2\2")
        buf.write(u"\2U\3\2\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2\2")
        buf.write(u"\2\2_\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2i\3\2\2\2\2k\3\2")
        buf.write(u"\2\2\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3")
        buf.write(u"\2\2\2\2w\3\2\2\2\3y\3\2\2\2\5|\3\2\2\2\7\u0082\3\2\2")
        buf.write(u"\2\t\u0084\3\2\2\2\13\u0086\3\2\2\2\r\u0088\3\2\2\2\17")
        buf.write(u"\u008a\3\2\2\2\21\u008c\3\2\2\2\23\u008e\3\2\2\2\25\u0090")
        buf.write(u"\3\2\2\2\27\u0092\3\2\2\2\31\u0094\3\2\2\2\33\u0096\3")
        buf.write(u"\2\2\2\35\u0098\3\2\2\2\37\u00d4\3\2\2\2!\u00d6\3\2\2")
        buf.write(u"\2#\u00db\3\2\2\2%\u00e0\3\2\2\2\'\u00e6\3\2\2\2)\u00eb")
        buf.write(u"\3\2\2\2+\u00ef\3\2\2\2-\u00f4\3\2\2\2/\u00f9\3\2\2\2")
        buf.write(u"\61\u00fe\3\2\2\2\63\u0103\3\2\2\2\65\u0108\3\2\2\2\67")
        buf.write(u"\u010d\3\2\2\29\u0115\3\2\2\2;\u011d\3\2\2\2=\u0125\3")
        buf.write(u"\2\2\2?\u012d\3\2\2\2A\u0135\3\2\2\2C\u013d\3\2\2\2E")
        buf.write(u"\u0143\3\2\2\2G\u0149\3\2\2\2I\u014f\3\2\2\2K\u0157\3")
        buf.write(u"\2\2\2M\u015f\3\2\2\2O\u0167\3\2\2\2Q\u016d\3\2\2\2S")
        buf.write(u"\u0174\3\2\2\2U\u017a\3\2\2\2W\u017f\3\2\2\2Y\u0185\3")
        buf.write(u"\2\2\2[\u018d\3\2\2\2]\u018f\3\2\2\2_\u0191\3\2\2\2a")
        buf.write(u"\u0193\3\2\2\2c\u0195\3\2\2\2e\u01a5\3\2\2\2g\u01a7\3")
        buf.write(u"\2\2\2i\u01ce\3\2\2\2k\u01d0\3\2\2\2m\u01d2\3\2\2\2o")
        buf.write(u"\u01d4\3\2\2\2q\u01d9\3\2\2\2s\u01db\3\2\2\2u\u01e0\3")
        buf.write(u"\2\2\2w\u01f2\3\2\2\2yz\7.\2\2z\4\3\2\2\2{}\t\2\2\2|")
        buf.write(u"{\3\2\2\2}~\3\2\2\2~|\3\2\2\2~\177\3\2\2\2\177\u0080")
        buf.write(u"\3\2\2\2\u0080\u0081\b\3\2\2\u0081\6\3\2\2\2\u0082\u0083")
        buf.write(u"\7-\2\2\u0083\b\3\2\2\2\u0084\u0085\7/\2\2\u0085\n\3")
        buf.write(u"\2\2\2\u0086\u0087\7,\2\2\u0087\f\3\2\2\2\u0088\u0089")
        buf.write(u"\7\61\2\2\u0089\16\3\2\2\2\u008a\u008b\7*\2\2\u008b\20")
        buf.write(u"\3\2\2\2\u008c\u008d\7+\2\2\u008d\22\3\2\2\2\u008e\u008f")
        buf.write(u"\7}\2\2\u008f\24\3\2\2\2\u0090\u0091\7\177\2\2\u0091")
        buf.write(u"\26\3\2\2\2\u0092\u0093\7]\2\2\u0093\30\3\2\2\2\u0094")
        buf.write(u"\u0095\7_\2\2\u0095\32\3\2\2\2\u0096\u0097\7~\2\2\u0097")
        buf.write(u"\34\3\2\2\2\u0098\u0099\7^\2\2\u0099\u009a\7n\2\2\u009a")
        buf.write(u"\u009b\7k\2\2\u009b\u009c\7o\2\2\u009c\36\3\2\2\2\u009d")
        buf.write(u"\u009e\7^\2\2\u009e\u009f\7v\2\2\u009f\u00d5\7q\2\2\u00a0")
        buf.write(u"\u00a1\7^\2\2\u00a1\u00a2\7t\2\2\u00a2\u00a3\7k\2\2\u00a3")
        buf.write(u"\u00a4\7i\2\2\u00a4\u00a5\7j\2\2\u00a5\u00a6\7v\2\2\u00a6")
        buf.write(u"\u00a7\7c\2\2\u00a7\u00a8\7t\2\2\u00a8\u00a9\7t\2\2\u00a9")
        buf.write(u"\u00aa\7q\2\2\u00aa\u00d5\7y\2\2\u00ab\u00ac\7^\2\2\u00ac")
        buf.write(u"\u00ad\7T\2\2\u00ad\u00ae\7k\2\2\u00ae\u00af\7i\2\2\u00af")
        buf.write(u"\u00b0\7j\2\2\u00b0\u00b1\7v\2\2\u00b1\u00b2\7c\2\2\u00b2")
        buf.write(u"\u00b3\7t\2\2\u00b3\u00b4\7t\2\2\u00b4\u00b5\7q\2\2\u00b5")
        buf.write(u"\u00d5\7y\2\2\u00b6\u00b7\7^\2\2\u00b7\u00b8\7n\2\2\u00b8")
        buf.write(u"\u00b9\7q\2\2\u00b9\u00ba\7p\2\2\u00ba\u00bb\7i\2\2\u00bb")
        buf.write(u"\u00bc\7t\2\2\u00bc\u00bd\7k\2\2\u00bd\u00be\7i\2\2\u00be")
        buf.write(u"\u00bf\7j\2\2\u00bf\u00c0\7v\2\2\u00c0\u00c1\7c\2\2\u00c1")
        buf.write(u"\u00c2\7t\2\2\u00c2\u00c3\7t\2\2\u00c3\u00c4\7q\2\2\u00c4")
        buf.write(u"\u00d5\7y\2\2\u00c5\u00c6\7^\2\2\u00c6\u00c7\7N\2\2\u00c7")
        buf.write(u"\u00c8\7q\2\2\u00c8\u00c9\7p\2\2\u00c9\u00ca\7i\2\2\u00ca")
        buf.write(u"\u00cb\7t\2\2\u00cb\u00cc\7k\2\2\u00cc\u00cd\7i\2\2\u00cd")
        buf.write(u"\u00ce\7j\2\2\u00ce\u00cf\7v\2\2\u00cf\u00d0\7c\2\2\u00d0")
        buf.write(u"\u00d1\7t\2\2\u00d1\u00d2\7t\2\2\u00d2\u00d3\7q\2\2\u00d3")
        buf.write(u"\u00d5\7y\2\2\u00d4\u009d\3\2\2\2\u00d4\u00a0\3\2\2\2")
        buf.write(u"\u00d4\u00ab\3\2\2\2\u00d4\u00b6\3\2\2\2\u00d4\u00c5")
        buf.write(u"\3\2\2\2\u00d5 \3\2\2\2\u00d6\u00d7\7^\2\2\u00d7\u00d8")
        buf.write(u"\7k\2\2\u00d8\u00d9\7p\2\2\u00d9\u00da\7v\2\2\u00da\"")
        buf.write(u"\3\2\2\2\u00db\u00dc\7^\2\2\u00dc\u00dd\7u\2\2\u00dd")
        buf.write(u"\u00de\7w\2\2\u00de\u00df\7o\2\2\u00df$\3\2\2\2\u00e0")
        buf.write(u"\u00e1\7^\2\2\u00e1\u00e2\7r\2\2\u00e2\u00e3\7t\2\2\u00e3")
        buf.write(u"\u00e4\7q\2\2\u00e4\u00e5\7f\2\2\u00e5&\3\2\2\2\u00e6")
        buf.write(u"\u00e7\7^\2\2\u00e7\u00e8\7n\2\2\u00e8\u00e9\7q\2\2\u00e9")
        buf.write(u"\u00ea\7i\2\2\u00ea(\3\2\2\2\u00eb\u00ec\7^\2\2\u00ec")
        buf.write(u"\u00ed\7n\2\2\u00ed\u00ee\7p\2\2\u00ee*\3\2\2\2\u00ef")
        buf.write(u"\u00f0\7^\2\2\u00f0\u00f1\7u\2\2\u00f1\u00f2\7k\2\2\u00f2")
        buf.write(u"\u00f3\7p\2\2\u00f3,\3\2\2\2\u00f4\u00f5\7^\2\2\u00f5")
        buf.write(u"\u00f6\7e\2\2\u00f6\u00f7\7q\2\2\u00f7\u00f8\7u\2\2\u00f8")
        buf.write(u".\3\2\2\2\u00f9\u00fa\7^\2\2\u00fa\u00fb\7v\2\2\u00fb")
        buf.write(u"\u00fc\7c\2\2\u00fc\u00fd\7p\2\2\u00fd\60\3\2\2\2\u00fe")
        buf.write(u"\u00ff\7^\2\2\u00ff\u0100\7e\2\2\u0100\u0101\7u\2\2\u0101")
        buf.write(u"\u0102\7e\2\2\u0102\62\3\2\2\2\u0103\u0104\7^\2\2\u0104")
        buf.write(u"\u0105\7u\2\2\u0105\u0106\7g\2\2\u0106\u0107\7e\2\2\u0107")
        buf.write(u"\64\3\2\2\2\u0108\u0109\7^\2\2\u0109\u010a\7e\2\2\u010a")
        buf.write(u"\u010b\7q\2\2\u010b\u010c\7v\2\2\u010c\66\3\2\2\2\u010d")
        buf.write(u"\u010e\7^\2\2\u010e\u010f\7c\2\2\u010f\u0110\7t\2\2\u0110")
        buf.write(u"\u0111\7e\2\2\u0111\u0112\7u\2\2\u0112\u0113\7k\2\2\u0113")
        buf.write(u"\u0114\7p\2\2\u01148\3\2\2\2\u0115\u0116\7^\2\2\u0116")
        buf.write(u"\u0117\7c\2\2\u0117\u0118\7t\2\2\u0118\u0119\7e\2\2\u0119")
        buf.write(u"\u011a\7e\2\2\u011a\u011b\7q\2\2\u011b\u011c\7u\2\2\u011c")
        buf.write(u":\3\2\2\2\u011d\u011e\7^\2\2\u011e\u011f\7c\2\2\u011f")
        buf.write(u"\u0120\7t\2\2\u0120\u0121\7e\2\2\u0121\u0122\7v\2\2\u0122")
        buf.write(u"\u0123\7c\2\2\u0123\u0124\7p\2\2\u0124<\3\2\2\2\u0125")
        buf.write(u"\u0126\7^\2\2\u0126\u0127\7c\2\2\u0127\u0128\7t\2\2\u0128")
        buf.write(u"\u0129\7e\2\2\u0129\u012a\7e\2\2\u012a\u012b\7u\2\2\u012b")
        buf.write(u"\u012c\7e\2\2\u012c>\3\2\2\2\u012d\u012e\7^\2\2\u012e")
        buf.write(u"\u012f\7c\2\2\u012f\u0130\7t\2\2\u0130\u0131\7e\2\2\u0131")
        buf.write(u"\u0132\7u\2\2\u0132\u0133\7g\2\2\u0133\u0134\7e\2\2\u0134")
        buf.write(u"@\3\2\2\2\u0135\u0136\7^\2\2\u0136\u0137\7c\2\2\u0137")
        buf.write(u"\u0138\7t\2\2\u0138\u0139\7e\2\2\u0139\u013a\7e\2\2\u013a")
        buf.write(u"\u013b\7q\2\2\u013b\u013c\7v\2\2\u013cB\3\2\2\2\u013d")
        buf.write(u"\u013e\7^\2\2\u013e\u013f\7u\2\2\u013f\u0140\7k\2\2\u0140")
        buf.write(u"\u0141\7p\2\2\u0141\u0142\7j\2\2\u0142D\3\2\2\2\u0143")
        buf.write(u"\u0144\7^\2\2\u0144\u0145\7e\2\2\u0145\u0146\7q\2\2\u0146")
        buf.write(u"\u0147\7u\2\2\u0147\u0148\7j\2\2\u0148F\3\2\2\2\u0149")
        buf.write(u"\u014a\7^\2\2\u014a\u014b\7v\2\2\u014b\u014c\7c\2\2\u014c")
        buf.write(u"\u014d\7p\2\2\u014d\u014e\7j\2\2\u014eH\3\2\2\2\u014f")
        buf.write(u"\u0150\7^\2\2\u0150\u0151\7c\2\2\u0151\u0152\7t\2\2\u0152")
        buf.write(u"\u0153\7u\2\2\u0153\u0154\7k\2\2\u0154\u0155\7p\2\2\u0155")
        buf.write(u"\u0156\7j\2\2\u0156J\3\2\2\2\u0157\u0158\7^\2\2\u0158")
        buf.write(u"\u0159\7c\2\2\u0159\u015a\7t\2\2\u015a\u015b\7e\2\2\u015b")
        buf.write(u"\u015c\7q\2\2\u015c\u015d\7u\2\2\u015d\u015e\7j\2\2\u015e")
        buf.write(u"L\3\2\2\2\u015f\u0160\7^\2\2\u0160\u0161\7c\2\2\u0161")
        buf.write(u"\u0162\7t\2\2\u0162\u0163\7v\2\2\u0163\u0164\7c\2\2\u0164")
        buf.write(u"\u0165\7p\2\2\u0165\u0166\7j\2\2\u0166N\3\2\2\2\u0167")
        buf.write(u"\u0168\7^\2\2\u0168\u0169\7u\2\2\u0169\u016a\7s\2\2\u016a")
        buf.write(u"\u016b\7t\2\2\u016b\u016c\7v\2\2\u016cP\3\2\2\2\u016d")
        buf.write(u"\u016e\7^\2\2\u016e\u016f\7v\2\2\u016f\u0170\7k\2\2\u0170")
        buf.write(u"\u0171\7o\2\2\u0171\u0172\7g\2\2\u0172\u0173\7u\2\2\u0173")
        buf.write(u"R\3\2\2\2\u0174\u0175\7^\2\2\u0175\u0176\7e\2\2\u0176")
        buf.write(u"\u0177\7f\2\2\u0177\u0178\7q\2\2\u0178\u0179\7v\2\2\u0179")
        buf.write(u"T\3\2\2\2\u017a\u017b\7^\2\2\u017b\u017c\7f\2\2\u017c")
        buf.write(u"\u017d\7k\2\2\u017d\u017e\7x\2\2\u017eV\3\2\2\2\u017f")
        buf.write(u"\u0180\7^\2\2\u0180\u0181\7h\2\2\u0181\u0182\7t\2\2\u0182")
        buf.write(u"\u0183\7c\2\2\u0183\u0184\7e\2\2\u0184X\3\2\2\2\u0185")
        buf.write(u"\u0186\7^\2\2\u0186\u0187\7o\2\2\u0187\u0188\7c\2\2\u0188")
        buf.write(u"\u0189\7v\2\2\u0189\u018a\7j\2\2\u018a\u018b\7k\2\2\u018b")
        buf.write(u"\u018c\7v\2\2\u018cZ\3\2\2\2\u018d\u018e\7a\2\2\u018e")
        buf.write(u"\\\3\2\2\2\u018f\u0190\7`\2\2\u0190^\3\2\2\2\u0191\u0192")
        buf.write(u"\7<\2\2\u0192`\3\2\2\2\u0193\u0194\t\2\2\2\u0194b\3\2")
        buf.write(u"\2\2\u0195\u0199\7f\2\2\u0196\u0198\5a\61\2\u0197\u0196")
        buf.write(u"\3\2\2\2\u0198\u019b\3\2\2\2\u0199\u019a\3\2\2\2\u0199")
        buf.write(u"\u0197\3\2\2\2\u019a\u01a3\3\2\2\2\u019b\u0199\3\2\2")
        buf.write(u"\2\u019c\u01a4\t\3\2\2\u019d\u019f\7^\2\2\u019e\u01a0")
        buf.write(u"\t\3\2\2\u019f\u019e\3\2\2\2\u01a0\u01a1\3\2\2\2\u01a1")
        buf.write(u"\u019f\3\2\2\2\u01a1\u01a2\3\2\2\2\u01a2\u01a4\3\2\2")
        buf.write(u"\2\u01a3\u019c\3\2\2\2\u01a3\u019d\3\2\2\2\u01a4d\3\2")
        buf.write(u"\2\2\u01a5\u01a6\t\3\2\2\u01a6f\3\2\2\2\u01a7\u01a8\t")
        buf.write(u"\4\2\2\u01a8h\3\2\2\2\u01a9\u01ab\5g\64\2\u01aa\u01a9")
        buf.write(u"\3\2\2\2\u01ab\u01ac\3\2\2\2\u01ac\u01aa\3\2\2\2\u01ac")
        buf.write(u"\u01ad\3\2\2\2\u01ad\u01b5\3\2\2\2\u01ae\u01af\7.\2\2")
        buf.write(u"\u01af\u01b0\5g\64\2\u01b0\u01b1\5g\64\2\u01b1\u01b2")
        buf.write(u"\5g\64\2\u01b2\u01b4\3\2\2\2\u01b3\u01ae\3\2\2\2\u01b4")
        buf.write(u"\u01b7\3\2\2\2\u01b5\u01b3\3\2\2\2\u01b5\u01b6\3\2\2")
        buf.write(u"\2\u01b6\u01cf\3\2\2\2\u01b7\u01b5\3\2\2\2\u01b8\u01ba")
        buf.write(u"\5g\64\2\u01b9\u01b8\3\2\2\2\u01ba\u01bd\3\2\2\2\u01bb")
        buf.write(u"\u01b9\3\2\2\2\u01bb\u01bc\3\2\2\2\u01bc\u01c5\3\2\2")
        buf.write(u"\2\u01bd\u01bb\3\2\2\2\u01be\u01bf\7.\2\2\u01bf\u01c0")
        buf.write(u"\5g\64\2\u01c0\u01c1\5g\64\2\u01c1\u01c2\5g\64\2\u01c2")
        buf.write(u"\u01c4\3\2\2\2\u01c3\u01be\3\2\2\2\u01c4\u01c7\3\2\2")
        buf.write(u"\2\u01c5\u01c3\3\2\2\2\u01c5\u01c6\3\2\2\2\u01c6\u01c8")
        buf.write(u"\3\2\2\2\u01c7\u01c5\3\2\2\2\u01c8\u01ca\7\60\2\2\u01c9")
        buf.write(u"\u01cb\5g\64\2\u01ca\u01c9\3\2\2\2\u01cb\u01cc\3\2\2")
        buf.write(u"\2\u01cc\u01ca\3\2\2\2\u01cc\u01cd\3\2\2\2\u01cd\u01cf")
        buf.write(u"\3\2\2\2\u01ce\u01aa\3\2\2\2\u01ce\u01bb\3\2\2\2\u01cf")
        buf.write(u"j\3\2\2\2\u01d0\u01d1\7?\2\2\u01d1l\3\2\2\2\u01d2\u01d3")
        buf.write(u"\7>\2\2\u01d3n\3\2\2\2\u01d4\u01d5\7^\2\2\u01d5\u01d6")
        buf.write(u"\7n\2\2\u01d6\u01d7\7g\2\2\u01d7\u01d8\7s\2\2\u01d8p")
        buf.write(u"\3\2\2\2\u01d9\u01da\7@\2\2\u01dar\3\2\2\2\u01db\u01dc")
        buf.write(u"\7^\2\2\u01dc\u01dd\7i\2\2\u01dd\u01de\7g\2\2\u01de\u01df")
        buf.write(u"\7s\2\2\u01dft\3\2\2\2\u01e0\u01e1\7#\2\2\u01e1v\3\2")
        buf.write(u"\2\2\u01e2\u01e9\7^\2\2\u01e3\u01e5\t\3\2\2\u01e4\u01e3")
        buf.write(u"\3\2\2\2\u01e5\u01e6\3\2\2\2\u01e6\u01e4\3\2\2\2\u01e6")
        buf.write(u"\u01e7\3\2\2\2\u01e7\u01ea\3\2\2\2\u01e8\u01ea\t\5\2")
        buf.write(u"\2\u01e9\u01e4\3\2\2\2\u01e9\u01e8\3\2\2\2\u01ea\u01f3")
        buf.write(u"\3\2\2\2\u01eb\u01ed\t\3\2\2\u01ec\u01eb\3\2\2\2\u01ed")
        buf.write(u"\u01ee\3\2\2\2\u01ee\u01ec\3\2\2\2\u01ee\u01ef\3\2\2")
        buf.write(u"\2\u01ef\u01f0\3\2\2\2\u01f0\u01f1\7^\2\2\u01f1\u01f3")
        buf.write(u"\t\6\2\2\u01f2\u01e2\3\2\2\2\u01f2\u01ec\3\2\2\2\u01f3")
        buf.write(u"x\3\2\2\2\22\2~\u00d4\u0199\u01a1\u01a3\u01ac\u01b5\u01bb")
        buf.write(u"\u01c5\u01cc\u01ce\u01e6\u01e9\u01ee\u01f2\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    ADD = 3
    SUB = 4
    MUL = 5
    DIV = 6
    L_PAREN = 7
    R_PAREN = 8
    L_BRACE = 9
    R_BRACE = 10
    L_BRACKET = 11
    R_BRACKET = 12
    BAR = 13
    FUNC_LIM = 14
    LIM_APPROACH_SYM = 15
    FUNC_INT = 16
    FUNC_SUM = 17
    FUNC_PROD = 18
    FUNC_LOG = 19
    FUNC_LN = 20
    FUNC_SIN = 21
    FUNC_COS = 22
    FUNC_TAN = 23
    FUNC_CSC = 24
    FUNC_SEC = 25
    FUNC_COT = 26
    FUNC_ARCSIN = 27
    FUNC_ARCCOS = 28
    FUNC_ARCTAN = 29
    FUNC_ARCCSC = 30
    FUNC_ARCSEC = 31
    FUNC_ARCCOT = 32
    FUNC_SINH = 33
    FUNC_COSH = 34
    FUNC_TANH = 35
    FUNC_ARSINH = 36
    FUNC_ARCOSH = 37
    FUNC_ARTANH = 38
    FUNC_SQRT = 39
    CMD_TIMES = 40
    CMD_CDOT = 41
    CMD_DIV = 42
    CMD_FRAC = 43
    CMD_MATHIT = 44
    UNDERSCORE = 45
    CARET = 46
    COLON = 47
    DIFFERENTIAL = 48
    LETTER = 49
    NUMBER = 50
    EQUAL = 51
    LT = 52
    LTE = 53
    GT = 54
    GTE = 55
    BANG = 56
    SYMBOL = 57

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'+'", u"'-'", u"'*'", u"'/'", u"'('", u"')'", u"'{'",
            u"'}'", u"'['", u"']'", u"'|'", u"'\\lim'", u"'\\int'", u"'\\sum'",
            u"'\\prod'", u"'\\log'", u"'\\ln'", u"'\\sin'", u"'\\cos'",
            u"'\\tan'", u"'\\csc'", u"'\\sec'", u"'\\cot'", u"'\\arcsin'",
            u"'\\arccos'", u"'\\arctan'", u"'\\arccsc'", u"'\\arcsec'",
            u"'\\arccot'", u"'\\sinh'", u"'\\cosh'", u"'\\tanh'", u"'\\arsinh'",
            u"'\\arcosh'", u"'\\artanh'", u"'\\sqrt'", u"'\\times'", u"'\\cdot'",
            u"'\\div'", u"'\\frac'", u"'\\mathit'", u"'_'", u"'^'", u"':'",
            u"'='", u"'<'", u"'\\leq'", u"'>'", u"'\\geq'", u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN", u"R_PAREN",
            u"L_BRACE", u"R_BRACE", u"L_BRACKET", u"R_BRACKET", u"BAR",
            u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT", u"FUNC_SUM",
            u"FUNC_PROD", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN", u"FUNC_COS",
            u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT", u"FUNC_ARCSIN",
            u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC", u"FUNC_ARCSEC",
            u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH",
            u"FUNC_ARCOSH", u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES",
            u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC", u"CMD_MATHIT", u"UNDERSCORE",
            u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER", u"NUMBER", u"EQUAL",
            u"LT", u"LTE", u"GT", u"GTE", u"BANG", u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN",
                  u"R_PAREN", u"L_BRACE", u"R_BRACE", u"L_BRACKET", u"R_BRACKET",
                  u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT",
                  u"FUNC_SUM", u"FUNC_PROD", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN",
                  u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT",
                  u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC",
                  u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH",
                  u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH", u"FUNC_ARTANH",
                  u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC",
                  u"CMD_MATHIT", u"UNDERSCORE", u"CARET", u"COLON", u"WS_CHAR",
                  u"DIFFERENTIAL", u"LETTER", u"DIGIT", u"NUMBER", u"EQUAL",
                  u"LT", u"LTE", u"GT", u"GTE", u"BANG", u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.8")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


