antlr:

	sudo apt install curl -y
	sudo apt install default-jdk
	curl -O https://www.antlr.org/download/antlr-4.8-complete.jar
	sudo mv antlr-4.8-complete.jar /usr/local/lib/
	sudo apt install virtualenv
	virtualenv /home/user/venv -p python3
	/bin/bash install.sh
run:
	/bin/bash run.sh
