import glob
import os

header = """
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
"""

output_dir = "_antlr"
for path in glob.glob(os.path.join(output_dir, "LaTeX*.*")) + glob.glob(
    os.path.join(output_dir, "latex*.*")
):
    offset = 0
    new_path = os.path.join(output_dir, os.path.basename(path).lower())
    with open(path, "r") as f:
        lines = [line.rstrip() + "\n" for line in f.readlines()]

    os.unlink(path)

    with open(new_path, "w") as out_file:
        if path.endswith(".py"):
            offset = 2
            out_file.write(header)
        out_file.writelines(lines[offset:])

    # debug("\t{}".format(new_path))
